on:
  push:
    branches:
      - main
      - preview

  jobs:
    deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    name: Deploy to Cloudflare Pages
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile
      - run: bun pages:build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .vercel/output/static --project-name=${{ secrets.CLOUDFLARE_PAGE_PROJECT_NAME }} --branch=${{ github.ref_name }}
